version: "2.4"

services:
  issuance-service:
    build:
      context: ./issuance-service
      dockerfile: Dockerfile
    expose:
      - "3001"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=256
    mem_limit: 380m
    mem_reservation: 192m
    cpus: 0.5
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  verification-service:
    build:
      context: ./verification-service
      dockerfile: Dockerfile
    expose:
      - "3002"
    environment:
      - NODE_ENV=production
      - ISSUANCE_SERVICE_URL=http://issuance-service:3001
      - NODE_OPTIONS=--max-old-space-size=256
    mem_limit: 380m
    mem_reservation: 192m
    cpus: 0.5
    depends_on:
      - issuance-service
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    mem_limit: 128m
    mem_reservation: 64m
    cpus: 0.25
    depends_on:
      - issuance-service
      - verification-service
    restart: unless-stopped
