version: '3.8'

services:
  # Issuance Service - Issues credentials
  issuance-service:
    build:
      context: ./issuance-service
      dockerfile: Dockerfile
    expose:
      - "3001"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=384
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 256M
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  # Verification Service - Verifies credentials  
  verification-service:
    build:
      context: ./verification-service
      dockerfile: Dockerfile
    expose:
      - "3002"
    environment:
      - NODE_ENV=production
      - ISSUANCE_SERVICE_URL=http://issuance-service:3001
      - NODE_OPTIONS=--max-old-space-size=384
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 256M
    depends_on:
      - issuance-service
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          memory: 64M
    depends_on:
      - issuance-service
      - verification-service
    restart: unless-stopped
