version: '3.8'

services:
  # Issuance Service - Issues credentials
  issuance-service:
    build:
      context: ./issuance-service
      dockerfile: Dockerfile
    expose:
      - "3001"
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data  # Shared database storage
    restart: unless-stopped

  # Verification Service - Verifies credentials  
  verification-service:
    build:
      context: ./verification-service
      dockerfile: Dockerfile
    expose:
      - "3002"
    environment:
      - NODE_ENV=production
      - ISSUANCE_SERVICE_URL=http://issuance-service:3001
    depends_on:
      - issuance-service
    restart: unless-stopped

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt
    restart: unless-stopped

volumes:
  npm-data:
  npm-letsencrypt:
